/*
 * Grafix_Thing.java
 */

import java.awt.*;

/**
 * Template code file for basic Java graphics
 *   Make sure to add all graphics code in the paint method,
 *   NOT the main method.
 *
 * @author Dr. Norman J. Bashias
 */
@SuppressWarnings("serial")
public class Grafix_Thing extends javax.swing.JFrame
{

    public void paint(Graphics g)
    {
        // draw the window title, menu, buttons
        super.paint(g);

        // get the Graphics context for the canvas
        Graphics pen = canvas.getGraphics();

        // *** add pen Graphics method calls after this line ***
        
        // draw a straight red line
    	pen.setColor( Color.RED );
    	pen.drawLine( 25, 30, 380, 66 );
    	
    	// draw empty and filled blue rectangles
    	pen.setColor( Color.BLUE );
    	pen.drawRect( 25, 100, 90, 55 );
    	pen.fillRect( 150, 100, 90, 55 );
    	
    	// clear a rectangular area
    	pen.clearRect(65, 70, 90, 55);
    	
    	// draw empty and filled cyan rectangles with rounded corners
    	pen.setColor( Color.CYAN );
    	pen.fillRoundRect( 300, 100, 90, 55, 50, 20 );
    	pen.drawRoundRect( 450, 100, 90, 55, 20, 50 );
    	
    	// draw empty raised and filled lowered yellow rectangles
    	pen.setColor( Color.YELLOW );
    	pen.draw3DRect( 25, 200, 90, 55, true );
    	pen.fill3DRect( 150, 200, 90, 55, false );
    	
    	// draw empty and filled magenta ovals
    	pen.setColor( Color.MAGENTA );
    	pen.drawOval( 300, 200, 90, 55 );
    	pen.fillOval( 450, 200, 90, 55 );
    	
    	// draw an empty arc starting at 0 and sweeping 360 degrees
    	pen.setColor( Color.RED );
    	pen.drawRect( 25, 355, 80, 80 );	// red bounding rectangle
    	pen.setColor( Color.BLACK );
    	pen.drawArc( 25, 355, 80, 80, 0, 360 );
    	
    	// draw an empty arc starting at 0 and sweeping 110 degrees
    	pen.setColor( Color.GREEN );
    	pen.drawRect( 110, 355, 80, 80 );	// green bounding rectangle
    	pen.setColor( Color.BLACK );
    	pen.drawArc( 110, 355, 80, 80, 0, 110 );
    	
    	// draw an empty arc starting at 0 and sweeping -270 degrees
    	pen.setColor( Color.BLUE );
    	pen.drawRect( 200, 355, 80, 80 );	// BLUE bounding rectangle
    	pen.setColor( Color.BLACK );
    	pen.drawArc( 200, 355, 80, 80, 0, -270 );
    	
    	// draw filled arc starting at 0 and sweeping 360 degrees
    	pen.fillArc( 25, 450, 80, 40, 0, 360 );
    	
    	// draw filled arc starting at 0 and sweeping -90 degrees
    	pen.fillArc( 110, 450, 80, 40, 0, -90 );
    	
    	// draw filled arc starting at 0 and sweeping -270 degrees
    	pen.fillArc( 200, 450, 80, 40, 0, -270 );
    	
    	// draw filled rectangle in my own color
    	Color myColor = new Color(52, 204, 235);
    	pen.setColor(myColor);
    	pen.fillRect(650, 100, 50, 150);
    	
    	pen.setColor(Color.black);
    	
    	Font myFont = new Font("Serif", Font.ITALIC|Font.BOLD, 30);
    	pen.setFont(myFont);
    	
    	pen.drawString("My Box", 650, 80);

        /**
         * *********************************************************
         * WARNING!!! DO NOT ADD OR MODIFY CODE BELOW THIS LINE!!! *
         * *********************************************************
         */
    } // end paint

    /**
     * Creates new form NB_Grafix_Thing2
     */
    public Grafix_Thing()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the NB_Grafix_Thing2 Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        canvas = new javax.swing.JPanel();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Drawing Form");

        canvas.setBackground(new java.awt.Color(255, 255, 255));
        canvas.setLayout(new java.awt.BorderLayout());
        getContentPane().add(canvas, java.awt.BorderLayout.CENTER);

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        repaint();
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Grafix_Thing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Grafix_Thing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Grafix_Thing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Grafix_Thing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Grafix_Thing().setVisible(true);
            }
        });
    } // end main method

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel canvas;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables
} // end Grafix_Thing class
